# -*- coding: utf-8 -*-
"""Dual-Branch + Attention + Signal Processing + Full Training + Plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JGwrRIrz5xnW27ILgAv76pIcMMzpFOEu
"""

# =========================================================
# 0️⃣ INSTALL
# =========================================================
!pip install -q timm albumentations==1.3.1 roboflow opencv-python seaborn

# =========================================================
# 1️⃣ IMPORTS
# =========================================================
import os, glob, random, cv2
import numpy as np
from collections import Counter
from PIL import Image
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

import albumentations as A
from albumentations.pytorch import ToTensorV2

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_recall_fscore_support

import timm
from roboflow import Roboflow

# =========================================================
# 2️⃣ SETUP
# =========================================================
device = "cuda" if torch.cuda.is_available() else "cpu"
print("🔥 Device:", device)

torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

# =========================================================
# 3️⃣ SIGNAL PROCESSING
# =========================================================
def enhance_fingerprint(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    img = clahe.apply(gray)

    img = cv2.GaussianBlur(img, (3,3), 0)

    sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
    sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

    img = cv2.magnitude(sobelx, sobely)
    img = cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX)

    img = np.stack([img,img,img], axis=-1).astype(np.uint8)
    return img

# =========================================================
# 4️⃣ DATA DOWNLOAD
# =========================================================
rf = Roboflow(api_key="I2du50GUFMWkImaaH0Wm")
project = rf.workspace("ahsan-khan-iw5ip").project("blood-group-detection-kmolp")
dataset = project.version(1).download("folder")
dataset_path = dataset.location

# =========================================================
# 5️⃣ LOAD DATA
# =========================================================
def load_all_data(path):
    files, labels = [], []
    classes = sorted(os.listdir(os.path.join(path, "train")))
    for i, cls in enumerate(classes):
        for split in ["train","valid","test"]:
            p = os.path.join(path, split, cls)
            if os.path.exists(p):
                imgs = glob.glob(p+"/*")
                files.extend(imgs)
                labels.extend([i]*len(imgs))
    return files, labels, classes

files, labels, classes = load_all_data(dataset_path)

X_train, X_tmp, y_train, y_tmp = train_test_split(
    files, labels, test_size=0.3, stratify=labels, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_tmp, y_tmp, test_size=0.5, stratify=y_tmp, random_state=42
)

cnt = Counter(y_train)

# =========================================================
# 6️⃣ AUGMENTATION
# =========================================================
train_tfms = A.Compose([
    A.Resize(224,224),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.4),
    A.ShiftScaleRotate(p=0.4),
    A.GaussNoise(p=0.2),
    A.Normalize(),
    ToTensorV2()
])

val_tfms = A.Compose([
    A.Resize(224,224),
    A.Normalize(),
    ToTensorV2()
])

# =========================================================
# 7️⃣ DATASET (DUAL INPUT)
# =========================================================
class DualDataset(Dataset):
    def __init__(self, files, labels, tfm):
        self.files = files
        self.labels = labels
        self.tfm = tfm

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        img = np.array(Image.open(self.files[idx]).convert("RGB"))

        raw_img = img.copy()
        signal_img = enhance_fingerprint(img)

        raw_img = self.tfm(image=raw_img)["image"]
        signal_img = self.tfm(image=signal_img)["image"]

        return raw_img, signal_img, torch.tensor(self.labels[idx])

# =========================================================
# 8️⃣ DATALOADER
# =========================================================
weights = [1.0/cnt[l] for l in y_train]
sampler = WeightedRandomSampler(weights, len(weights))

train_dl = DataLoader(DualDataset(X_train,y_train,train_tfms),
                      batch_size=32, sampler=sampler)

val_dl = DataLoader(DualDataset(X_val,y_val,val_tfms),
                    batch_size=64)

test_dl = DataLoader(DualDataset(X_test,y_test,val_tfms),
                     batch_size=64)

# =========================================================
# 9️⃣ ATTENTION FUSION
# =========================================================
class AttentionFusion(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.attn = nn.Sequential(
            nn.Linear(dim*2, dim),
            nn.ReLU(),
            nn.Linear(dim, 2),
            nn.Softmax(dim=1)
        )

    def forward(self, f1, f2):
        weights = self.attn(torch.cat([f1,f2], dim=1))
        w1 = weights[:,0].unsqueeze(1)
        w2 = weights[:,1].unsqueeze(1)
        return w1*f1 + w2*f2

# =========================================================
# 🔟 MODEL
# =========================================================
class DualBranchNet(nn.Module):
    def __init__(self, num_classes):
        super().__init__()

        self.raw = timm.create_model("tf_efficientnetv2_s", pretrained=True, num_classes=0)
        self.signal = timm.create_model("tf_efficientnetv2_s", pretrained=True, num_classes=0)

        dim = self.raw.num_features

        self.fusion = AttentionFusion(dim)

        self.fc = nn.Sequential(
            nn.Linear(dim,512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(512,num_classes)
        )

    def forward(self, x1, x2):
        f1 = self.raw(x1)
        f2 = self.signal(x2)
        fused = self.fusion(f1,f2)
        return self.fc(fused)

model = DualBranchNet(len(classes)).to(device)

# =========================================================
# 1️⃣1️⃣ LOSS + OPTIMIZER
# =========================================================
class_weights = torch.tensor(
    [1.0/cnt[i] for i in range(len(classes))],
    device=device
)

criterion = nn.CrossEntropyLoss(weight=class_weights, label_smoothing=0.1)
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20)

# =========================================================
# 1️⃣2️⃣ TRAINING + EARLY STOPPING
# =========================================================
EPOCHS = 30
best_val = 0
patience = 5
counter = 0

train_acc_hist, val_acc_hist = [], []
train_loss_hist, val_loss_hist = [], []
lr_hist = []

for epoch in range(EPOCHS):
    model.train()
    tp, ty = [], []
    running_loss = 0

    for raw, signal, y in tqdm(train_dl):
        raw, signal, y = raw.to(device), signal.to(device), y.to(device)

        optimizer.zero_grad()
        out = model(raw, signal)
        loss = criterion(out, y)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        tp += out.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()

    scheduler.step()
    lr_hist.append(optimizer.param_groups[0]["lr"])

    train_loss = running_loss / len(train_dl)
    train_acc = accuracy_score(ty, tp)

    # VALIDATION
    model.eval()
    vp, vy = [], []
    val_loss = 0

    with torch.no_grad():
        for raw, signal, y in val_dl:
            raw, signal, y = raw.to(device), signal.to(device), y.to(device)
            out = model(raw, signal)
            loss = criterion(out, y)

            val_loss += loss.item()
            vp += out.argmax(1).cpu().tolist()
            vy += y.cpu().tolist()

    val_loss /= len(val_dl)
    val_acc = accuracy_score(vy, vp)

    train_acc_hist.append(train_acc)
    val_acc_hist.append(val_acc)
    train_loss_hist.append(train_loss)
    val_loss_hist.append(val_loss)

    print(f"Epoch {epoch+1}: Train={train_acc:.4f} | Val={val_acc:.4f}")

    if val_acc > best_val:
        best_val = val_acc
        torch.save(model.state_dict(),"best_dual_model.pth")
        counter = 0
        print("✅ Best model saved")
    else:
        counter += 1
        if counter >= patience:
            print("⛔ Early stopping triggered")
            break

# =========================================================
# 1️⃣3️⃣ TESTING
# =========================================================
model.load_state_dict(torch.load("best_dual_model.pth"))
model.eval()

tp, ty = [], []

with torch.no_grad():
    for raw, signal, y in test_dl:
        raw, signal, y = raw.to(device), signal.to(device), y.to(device)
        out = model(raw, signal)

        tp += out.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()

print("\n🎯 TEST ACC:", accuracy_score(ty,tp))
print("\n📄 CLASSIFICATION REPORT:\n")
print(classification_report(ty,tp,target_names=classes))

# =========================================================
# 📊 CONFUSION MATRIX
# =========================================================
cm = confusion_matrix(ty,tp)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# =========================================================
# 📊 CLASS METRICS
# =========================================================
precision, recall, f1, _ = precision_recall_fscore_support(ty,tp)
x = np.arange(len(classes))

plt.figure(figsize=(10,5))
plt.bar(x-0.2, precision, 0.2, label='Precision')
plt.bar(x, recall, 0.2, label='Recall')
plt.bar(x+0.2, f1, 0.2, label='F1')
plt.xticks(x, classes)
plt.legend()
plt.title("Class-wise Performance")
plt.show()

# =========================================================
# 📈 TRAINING CURVES
# =========================================================
epochs_range = range(1,len(train_acc_hist)+1)

plt.figure(figsize=(18,5))

plt.subplot(1,3,1)
plt.plot(epochs_range, train_acc_hist, label='Train')
plt.plot(epochs_range, val_acc_hist, label='Val')
plt.legend()
plt.title("Accuracy")

plt.subplot(1,3,2)
plt.plot(epochs_range, train_loss_hist, label='Train')
plt.plot(epochs_range, val_loss_hist, label='Val')
plt.legend()
plt.title("Loss")

plt.subplot(1,3,3)
plt.plot(lr_hist)
plt.title("Learning Rate")

plt.tight_layout()
plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

# Binarize labels
y_true_bin = label_binarize(ty, classes=list(range(len(classes))))

# Get probabilities
model.eval()
probs = []

with torch.no_grad():
    for raw, signal, y in test_dl:
        raw, signal = raw.to(device), signal.to(device)
        out = model(raw, signal)
        probs.append(torch.softmax(out, dim=1).cpu().numpy())

y_score = np.concatenate(probs)

# ROC
plt.figure(figsize=(8,6))
for i in range(len(classes)):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{classes[i]} (AUC={roc_auc:.2f})")

plt.plot([0,1],[0,1],'k--')
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("ROC Curve")
plt.legend()
plt.show()

from sklearn.metrics import precision_recall_curve

plt.figure(figsize=(8,6))

for i in range(len(classes)):
    precision, recall, _ = precision_recall_curve(
        y_true_bin[:, i], y_score[:, i]
    )
    plt.plot(recall, precision, label=classes[i])

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.show()

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print("Total Params:", total_params)
print("Trainable Params:", trainable_params)

import time

model.eval()
start = time.time()

with torch.no_grad():
    for raw, signal, _ in test_dl:
        raw, signal = raw.to(device), signal.to(device)
        _ = model(raw, signal)

end = time.time()

print("Total Inference Time:", end - start)
print("Avg per image:", (end-start)/len(X_test))

from sklearn.metrics import precision_score, recall_score, f1_score

print("Macro Precision:", precision_score(ty, tp, average='macro'))
print("Macro Recall:", recall_score(ty, tp, average='macro'))
print("Macro F1:", f1_score(ty, tp, average='macro'))

print("Weighted Precision:", precision_score(ty, tp, average='weighted'))
print("Weighted Recall:", recall_score(ty, tp, average='weighted'))
print("Weighted F1:", f1_score(ty, tp, average='weighted'))

from sklearn.metrics import top_k_accuracy_score

print("Top-2 Accuracy:", top_k_accuracy_score(ty, y_score, k=2))
print("Top-3 Accuracy:", top_k_accuracy_score(ty, y_score, k=3))

from sklearn.metrics import log_loss

print("Log Loss:", log_loss(ty, y_score))

from sklearn.metrics import cohen_kappa_score

print("Cohen Kappa:", cohen_kappa_score(ty, tp))

def add_noise(img):
    noise = np.random.normal(0, 25, img.shape)
    return np.clip(img + noise, 0, 255).astype(np.uint8)

def blur_image(img):
    return cv2.GaussianBlur(img, (7,7), 0)

def occlude(img):
    h, w, _ = img.shape
    img[h//4:h//2, w//4:w//2] = 0
    return img

fps = len(X_test) / (end - start)
print("FPS:", fps)

print(torch.cuda.memory_allocated()/1024**2, "MB")

torch.save(model.state_dict(), "temp.pth")
import os
print("Model Size (MB):", os.path.getsize("temp.pth")/1e6)

!pip install grad-cam

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

# Wrapper model
class GradCAMWrapper(torch.nn.Module):
    def __init__(self, model, signal):
        super().__init__()
        self.model = model
        self.signal = signal

    def forward(self, x):
        return self.model(x, self.signal)

# Take one batch
raw_sample, signal_sample, _ = next(iter(test_dl))

raw_sample = raw_sample[0].unsqueeze(0).to(device)
signal_sample = signal_sample[0].unsqueeze(0).to(device)

# Wrap model
wrapped_model = GradCAMWrapper(model, signal_sample)

# Target layer (EfficientNet last block)
target_layer = model.raw.blocks[-1]

cam = GradCAM(model=wrapped_model, target_layers=[target_layer])

grayscale_cam = cam(input_tensor=raw_sample)

# Convert to image
raw_img = raw_sample.squeeze().permute(1,2,0).cpu().numpy()
raw_img = (raw_img - raw_img.min()) / (raw_img.max() - raw_img.min())

cam_image = show_cam_on_image(raw_img, grayscale_cam[0], use_rgb=True)

plt.imshow(cam_image)
plt.title("Grad-CAM Visualization")
plt.axis("off")
plt.show()

from sklearn.calibration import calibration_curve

prob_true, prob_pred = calibration_curve(
    (np.array(ty) == 0).astype(int),
    y_score[:,0],
    n_bins=10
)

plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0,1],[0,1],'--')
plt.title("Calibration Curve")
plt.xlabel("Predicted Probability")
plt.ylabel("True Probability")
plt.show()

misclassified = [(i, t, p) for i,(t,p) in enumerate(zip(ty,tp)) if t!=p]

print("Total Misclassified:", len(misclassified))
print("Sample Errors:", misclassified[:10])

confidence = np.max(y_score, axis=1)

plt.hist(confidence, bins=20)
plt.title("Prediction Confidence Distribution")
plt.xlabel("Confidence")
plt.ylabel("Frequency")
plt.show()

class_acc = {}

for i in range(len(classes)):
    idx = [j for j in range(len(ty)) if ty[j] == i]
    correct = sum([1 for j in idx if ty[j] == tp[j]])
    class_acc[classes[i]] = correct / len(idx)

print(class_acc)

import matplotlib.pyplot as plt

# Compute class-wise accuracy
class_acc = {}

for i in range(len(classes)):
    idx = [j for j in range(len(ty)) if ty[j] == i]
    correct = sum([1 for j in idx if ty[j] == tp[j]])
    class_acc[classes[i]] = correct / len(idx)

# Convert to lists
labels = list(class_acc.keys())
values = list(class_acc.values())

# Plot
plt.figure(figsize=(10,5))
bars = plt.bar(labels, values)

# Add values on top of bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01,
             f"{yval:.2f}", ha='center', fontsize=10)

plt.ylim(0, 1.05)
plt.title("Class-wise Accuracy")
plt.xlabel("Classes")
plt.ylabel("Accuracy")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

for i, t, p in misclassified[:5]:
    img = Image.open(X_test[i])
    plt.imshow(img)
    plt.title(f"True: {classes[t]} | Pred: {classes[p]}")
    plt.axis("off")
    plt.show()

features = []

model.eval()
with torch.no_grad():
    for raw, signal, _ in test_dl:
        raw = raw.to(device)
        f = model.raw(raw)
        features.append(torch.norm(f, dim=1).cpu().numpy())

features = np.concatenate(features)

plt.hist(features, bins=30)
plt.title("Feature Magnitude Distribution")
plt.show()

# =========================================================
# 🔥 COMPLETE RESULTS SECTION (ALL-IN-ONE)
# =========================================================

import time
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    precision_recall_fscore_support, roc_curve, auc,
    precision_recall_curve, log_loss, cohen_kappa_score,
    top_k_accuracy_score
)
from sklearn.preprocessing import label_binarize

# =========================================================
# 1️⃣ TEST EVALUATION
# =========================================================
model.load_state_dict(torch.load("best_dual_model.pth"))
model.eval()

tp, ty = [], []
probs = []

start = time.time()

with torch.no_grad():
    for raw, signal, y in test_dl:
        raw, signal = raw.to(device), signal.to(device)
        out = model(raw, signal)

        tp += out.argmax(1).cpu().tolist()
        ty += y.cpu().tolist()
        probs.append(torch.softmax(out, dim=1).cpu().numpy())

end = time.time()

y_score = np.concatenate(probs)

# =========================================================
# 2️⃣ BASIC METRICS
# =========================================================
print("\n🎯 TEST ACCURACY:", accuracy_score(ty, tp))
print("\n📄 CLASSIFICATION REPORT:\n")
print(classification_report(ty, tp, target_names=classes))

print("\n📊 ADDITIONAL METRICS")
print("Macro F1:", precision_recall_fscore_support(ty, tp, average='macro')[2])
print("Weighted F1:", precision_recall_fscore_support(ty, tp, average='weighted')[2])
print("Cohen Kappa:", cohen_kappa_score(ty, tp))
print("Log Loss:", log_loss(ty, y_score))
print("Top-2 Acc:", top_k_accuracy_score(ty, y_score, k=2))
print("Top-3 Acc:", top_k_accuracy_score(ty, y_score, k=3))

# =========================================================
# 3️⃣ CONFUSION MATRIX
# =========================================================
cm = confusion_matrix(ty, tp)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.savefig("confusion_matrix.png", dpi=300)
plt.show()

# =========================================================
# 4️⃣ CLASS-WISE METRICS
# =========================================================
precision, recall, f1, _ = precision_recall_fscore_support(ty, tp)

x = np.arange(len(classes))

plt.figure(figsize=(10,5))
plt.bar(x-0.2, precision, 0.2, label='Precision')
plt.bar(x, recall, 0.2, label='Recall')
plt.bar(x+0.2, f1, 0.2, label='F1')
plt.xticks(x, classes)
plt.legend()
plt.title("Class-wise Metrics")
plt.savefig("class_metrics.png", dpi=300)
plt.show()

# =========================================================
# 5️⃣ CLASS-WISE ACCURACY (WITH VALUES)
# =========================================================
class_acc = {}
for i in range(len(classes)):
    idx = [j for j in range(len(ty)) if ty[j] == i]
    correct = sum([1 for j in idx if ty[j] == tp[j]])
    class_acc[classes[i]] = correct / len(idx)

labels = list(class_acc.keys())
values = list(class_acc.values())

plt.figure(figsize=(10,5))
bars = plt.bar(labels, values)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x()+bar.get_width()/2, yval+0.01,
             f"{yval:.2f}", ha='center')

plt.ylim(0,1.05)
plt.title("Class-wise Accuracy")
plt.savefig("class_accuracy.png", dpi=300)
plt.show()

# =========================================================
# 6️⃣ ROC + AUC
# =========================================================
y_true_bin = label_binarize(ty, classes=list(range(len(classes))))

plt.figure(figsize=(8,6))
for i in range(len(classes)):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{classes[i]} (AUC={roc_auc:.2f})")

plt.plot([0,1],[0,1],'--')
plt.legend()
plt.title("ROC Curve")
plt.savefig("roc_curve.png", dpi=300)
plt.show()

# =========================================================
# 7️⃣ PRECISION-RECALL CURVE
# =========================================================
plt.figure(figsize=(8,6))
for i in range(len(classes)):
    p, r, _ = precision_recall_curve(y_true_bin[:, i], y_score[:, i])
    plt.plot(r, p, label=classes[i])

plt.legend()
plt.title("Precision-Recall Curve")
plt.savefig("pr_curve.png", dpi=300)
plt.show()

# =========================================================
# 8️⃣ CONFIDENCE DISTRIBUTION
# =========================================================
confidence = np.max(y_score, axis=1)

plt.hist(confidence, bins=20)
plt.title("Confidence Distribution")
plt.savefig("confidence.png", dpi=300)
plt.show()

# =========================================================
# 9️⃣ ERROR ANALYSIS
# =========================================================
errors = [(i,t,p) for i,(t,p) in enumerate(zip(ty,tp)) if t!=p]

print("\n❌ Total Errors:", len(errors))
print("Sample Errors:", errors[:10])

# =========================================================
# 🔟 MODEL COMPLEXITY
# =========================================================
total_params = sum(p.numel() for p in model.parameters())
print("\n⚙️ Total Parameters:", total_params)

# =========================================================
# 1️⃣1️⃣ INFERENCE SPEED
# =========================================================
total_time = end - start
print("\n⏱️ Total Time:", total_time)
print("⚡ FPS:", len(X_test)/total_time)
print("🧠 Time per image:", total_time/len(X_test))

# =========================================================
# 🔥 FIXED MODEL ARCHITECTURE ANALYSIS (ALL-IN-ONE)
# =========================================================

!pip install -q torchinfo torchviz

import torch
import matplotlib.pyplot as plt
from torchinfo import summary
from torchviz import make_dot

# =========================================================
# 1️⃣ PRINT FULL MODEL
# =========================================================
print("\n================ FULL MODEL =================\n")
print(model)

# =========================================================
# 2️⃣ FIXED MODEL SUMMARY (IMPORTANT FIX)
# =========================================================
print("\n================ MODEL SUMMARY =================\n")

# Create dummy inputs (NOT shapes)
raw_input = torch.randn(1,3,224,224).to(device)
signal_input = torch.randn(1,3,224,224).to(device)

summary(
    model,
    input_data=(raw_input, signal_input),   # ✅ FIXED
    col_names=["input_size","output_size","num_params"],
    depth=3
)

# =========================================================
# 3️⃣ BLOCK-LEVEL BREAKDOWN
# =========================================================
print("\n================ RAW BRANCH BLOCKS =================\n")
for i, block in enumerate(model.raw.blocks):
    print(f"Block {i}: {block}\n")

print("\n================ SIGNAL BRANCH BLOCKS =================\n")
for i, block in enumerate(model.signal.blocks):
    print(f"Block {i}: {block}\n")

# =========================================================
# 4️⃣ IMPORTANT COMPONENTS
# =========================================================
print("\n================ FUSION MODULE =================\n")
print(model.fusion)

print("\n================ CLASSIFIER HEAD =================\n")
print(model.fc)

# =========================================================
# 5️⃣ PARAMETER DISTRIBUTION
# =========================================================
params = {
    "Raw Branch": sum(p.numel() for p in model.raw.parameters()),
    "Signal Branch": sum(p.numel() for p in model.signal.parameters()),
    "Fusion": sum(p.numel() for p in model.fusion.parameters()),
    "Classifier": sum(p.numel() for p in model.fc.parameters()),
}

print("\n================ PARAMETER COUNT =================\n")
for k,v in params.items():
    print(f"{k}: {v}")

plt.figure(figsize=(8,5))
plt.bar(params.keys(), params.values())
plt.title("Parameter Distribution")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig("parameter_distribution.png", dpi=300)
plt.show()

# =========================================================
# 6️⃣ MODEL GRAPH (SAVE AS IMAGE)
# =========================================================
print("\n================ GENERATING MODEL GRAPH =================\n")

out = model(raw_input, signal_input)

dot = make_dot(out, params=dict(model.named_parameters()))
dot.render("model_architecture", format="png")

print("✅ Saved as: model_architecture.png")

# =========================================================
# 🔥 SIGNAL PROCESSING VISUALIZATION (FOR PAPER)
# =========================================================

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

def show_signal_processing_samples(files, n=8):
    np.random.seed(42)
    sample_paths = np.random.choice(files, size=min(n, len(files)), replace=False)

    cols = 2
    rows = len(sample_paths)

    plt.figure(figsize=(6, 3 * rows))
    plt.suptitle("Signal Processing Visualization (Original vs Enhanced)", fontsize=16)

    for i, path in enumerate(sample_paths):
        # Load original
        original = np.array(Image.open(path).convert("RGB"))

        # Apply your signal processing
        enhanced = enhance_fingerprint(original)

        # Normalize for display
        original_disp = original / 255.0
        enhanced_disp = enhanced / 255.0

        # Plot Original
        plt.subplot(rows, cols, 2*i + 1)
        plt.imshow(original_disp)
        plt.title("Original")
        plt.axis("off")

        # Plot Enhanced
        plt.subplot(rows, cols, 2*i + 2)
        plt.imshow(enhanced_disp)
        plt.title("Signal Enhanced")
        plt.axis("off")

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig("signal_processing_visualization.png", dpi=300)
    plt.show()

# Run it
show_signal_processing_samples(X_test, n=8)

def debug_signal_pipeline(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    clahe = cv2.createCLAHE(2.0,(8,8))
    clahe_img = clahe.apply(gray)

    blur = cv2.GaussianBlur(clahe_img, (3,3), 0)

    sobelx = cv2.Sobel(blur, cv2.CV_64F, 1, 0)
    sobely = cv2.Sobel(blur, cv2.CV_64F, 0, 1)
    magnitude = cv2.magnitude(sobelx, sobely)

    norm = cv2.normalize(magnitude, None, 0, 255, cv2.NORM_MINMAX)

    return gray, clahe_img, blur, magnitude, norm

# visualize one sample
img = np.array(Image.open(X_test[0]).convert("RGB"))
steps = debug_signal_pipeline(img)

titles = ["Gray", "CLAHE", "Blur", "Gradient", "Normalized"]

plt.figure(figsize=(12,3))
for i, (step, title) in enumerate(zip(steps, titles)):
    plt.subplot(1,5,i+1)
    plt.imshow(step, cmap='gray')
    plt.title(title)
    plt.axis("off")

plt.tight_layout()
plt.savefig("signal_pipeline_steps.png", dpi=300)
plt.show()

# =========================================================
# 🔥 COMBINED VISUALIZATION (ORIGINAL + ENHANCED + GRAD-CAM)
# =========================================================

!pip install -q grad-cam

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import torch
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

# =========================================================
# Wrapper for GradCAM (dual input fix)
# =========================================================
class GradCAMWrapper(torch.nn.Module):
    def __init__(self, model, signal):
        super().__init__()
        self.model = model
        self.signal = signal

    def forward(self, x):
        return self.model(x, self.signal)

# =========================================================
# FUNCTION: VISUALIZE COMBINED RESULTS
# =========================================================
def visualize_combined(model, files, n=5):
    model.eval()
    np.random.seed(42)

    sample_paths = np.random.choice(files, size=min(n, len(files)), replace=False)

    plt.figure(figsize=(12, 4*n))
    plt.suptitle("Original vs Enhanced vs Grad-CAM", fontsize=16)

    for i, path in enumerate(sample_paths):
        # Load image
        original = np.array(Image.open(path).convert("RGB"))

        # Signal enhanced
        enhanced = enhance_fingerprint(original)

        # Preprocess
        raw_tensor = val_tfms(image=original)["image"].unsqueeze(0).to(device)
        signal_tensor = val_tfms(image=enhanced)["image"].unsqueeze(0).to(device)

        # Wrapper
        wrapped_model = GradCAMWrapper(model, signal_tensor)

        # Target layer (EfficientNet last block)
        target_layer = model.raw.blocks[-1]

        cam = GradCAM(model=wrapped_model, target_layers=[target_layer])

        grayscale_cam = cam(input_tensor=raw_tensor)[0]

        # Prepare image for overlay
        raw_img = raw_tensor.squeeze().permute(1,2,0).cpu().numpy()
        raw_img = (raw_img - raw_img.min()) / (raw_img.max() - raw_img.min())

        cam_image = show_cam_on_image(raw_img, grayscale_cam, use_rgb=True)

        # Prediction
        with torch.no_grad():
            out = model(raw_tensor, signal_tensor)
            prob = torch.softmax(out, dim=1)
            pred = prob.argmax(1).item()
            conf = prob.max().item()

        # Plot Original
        plt.subplot(n, 3, i*3 + 1)
        plt.imshow(original)
        plt.title("Original")
        plt.axis("off")

        # Plot Enhanced
        plt.subplot(n, 3, i*3 + 2)
        plt.imshow(enhanced)
        plt.title("Enhanced")
        plt.axis("off")

        # Plot Grad-CAM
        plt.subplot(n, 3, i*3 + 3)
        plt.imshow(cam_image)
        plt.title(f"Grad-CAM\n{classes[pred]} ({conf:.2f})")
        plt.axis("off")

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig("combined_visualization.png", dpi=300)
    plt.show()

# =========================================================
# RUN
# =========================================================
visualize_combined(model, X_test, n=5)